# Generated by Django 5.2.17 on 2026-10-06 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_product_image_product_video_url_user_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='zone',
            field=models.CharField(default='outside_dhaka', max_length=14),
        ),
    ]
