# Generated by Django 5.2.17 on 2026-10-07 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_categories_subcategories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField(blank=True, max_length=2000)),
                ('pinned', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-pinned', '-id'],
            },
        ),
        migrations.RemoveField(
            model_name='order',
            name='consignment_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='courier_status',
        ),
        migrations.RemoveField(
            model_name='order',
            name='tracking',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddConstraint(
            model_name='ledger',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'return_fee')), fields=('kind', 'ref'), name='one_return_fee_per_order'),
        ),
    ]
