# Generated by Django 5.2.17 on 2026-10-09 01:58

import django.db.models.deletion
from django.db import migrations, models


def fill_data(apps, schema_editor):
    """The old stock number becomes in stock / out of stock, and existing order lines get the product name, category and sub category saved on them."""
    Product = apps.get_model("shop", "Product")
    OrderItem = apps.get_model("shop", "OrderItem")
    Product.objects.filter(stock__lte=0).update(in_stock=False)
    for it in OrderItem.objects.select_related("product__subcategory__category").iterator():
        p = it.product
        if p is None:
            continue
        it.name = p.name
        it.subcategory = p.subcategory.name
        it.category = p.subcategory.category.name if p.subcategory.category_id else ""
        it.size = ""
        it.color = ""
        it.save(update_fields=["name", "subcategory", "category", "size", "color"])


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['position', '-id']},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['position', 'name'], 'verbose_name_plural': 'sub categories'},
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='category',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='subcategory',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(fields=('user', 'product', 'size', 'color'), name='one_cart_line_per_variant'),
        ),
        migrations.RunPython(fill_data, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
